name: FINAL_KEY_EXTRACTOR
on: [push, workflow_dispatch]
jobs:
  show-me-the-money:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: PRINT SHA1
        run: |
          cd android && chmod +x gradlew
          echo "ğŸ‘‡ğŸ‘‡ğŸ‘‡ COPIA LA RIGA SOTTO QUESTA ğŸ‘‡ğŸ‘‡ğŸ‘‡"
          ./gradlew signingReport | grep "SHA1" | head -n 1
          echo "ğŸ‘†ğŸ‘†ğŸ‘† COPIA LA RIGA SOPRA QUESTA ğŸ‘†ğŸ‘†ğŸ‘†"
